name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
        docker login --username martinbergendorff --password ${{ secrets.GHCR_PAT }} ghcr.io
        docker build . --tag ghcr.io/martinbergendorff/someconsoleapp:latest
        docker push ghcr.io/martinbergendorff/someconsoleapp:latest
